# Generated by Django 6.0.3 on 2026-03-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_data_adicionada_produtos_pro_data_adicionada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['-pro_descricao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
