# Generated by Django 6.0.3 on 2026-03-12 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produtos_pro_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_nome', models.CharField(max_length=10, verbose_name='Nome')),
                ('uni_sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('uni_data_adicionada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['-uni_nome'],
            },
        ),
        migrations.AlterField(
            model_name='produtos',
            name='pro_referencia',
            field=models.CharField(default='SEM-REF', max_length=20, verbose_name='Referência'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='pro_unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produtos.unidades', verbose_name='Unidade'),
        ),
    ]
