# Generated by Django 6.0.3 on 2026-03-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_unidades_alter_produtos_pro_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='pro_data_modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unidades',
            name='uni_data_modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='pro_descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
