# Generated by Django 6.0.3 on 2026-03-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produtos_pro_data_modificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='pro_saldo',
            field=models.IntegerField(default=0, verbose_name='Saldo'),
        ),
    ]
