# Generated by Django 6.0.3 on 2026-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produtos_pro_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='pro_preco',
        ),
        migrations.AddField(
            model_name='produtos',
            name='pro_custo_medio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='movimentacoes.Movimentacao'),
            preserve_default=False,
        ),
    ]
