# Generated by Django 6.0.3 on 2026-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_produtos_pro_preco_produtos_pro_custo_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='pro_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo'),
        ),
    ]
