# Generated by Django 6.0.3 on 2026-04-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produtos_pro_saldo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['pro_descricao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='unidades',
            options={'ordering': ['uni_nome'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterField(
            model_name='produtos',
            name='pro_custo_medio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Médio'),
        ),
    ]
