# Generated by Django 6.0.3 on 2026-04-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_produtos_options_alter_unidades_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={},
        ),
    ]
