# Generated by Django 6.0.3 on 2026-04-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_produtos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['pro_descricao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
