# Generated by Django 6.0.3 on 2026-03-30 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0007_produtos_pro_saldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_quantidade', models.PositiveIntegerField(verbose_name='Quantidade relativa à Unidade de Medida')),
                ('mov_tipo', models.CharField(choices=[('E', 'Entradas'), ('S', 'Saídas')], max_length=1)),
                ('mov_data_adicionada', models.DateTimeField(auto_now_add=True)),
                ('mov_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produtos')),
                ('mov_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-mov_data_adicionada'],
            },
        ),
    ]
