# Generated by Django 6.0.3 on 2026-03-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='mov_tipo',
            field=models.CharField(choices=[('E', 'Entradas'), ('S', 'Saídas')], max_length=1, verbose_name='Tipo de Movimentação'),
        ),
    ]
