# Generated by Django 6.0.3 on 2026-03-31 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_alter_movimentacao_mov_tipo'),
        ('produtos', '0007_produtos_pro_saldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='mov_saldo_momento',
            field=models.IntegerField(editable=False, null=True, verbose_name='Saldo no momento:'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='mov_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produtos', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='mov_tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='mov_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
