# Generated by Django 6.0.3 on 2026-03-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_movimentacao_mov_saldo_momento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='mov_saldo_momento',
            new_name='mov_saldo_movimento',
        ),
    ]
