# Generated by Django 6.0.3 on 2026-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_rename_mov_saldo_momento_movimentacao_mov_saldo_movimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='mov_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo'),
        ),
    ]
