# Generated by Django 6.0.3 on 2026-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0005_movimentacao_mov_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='mov_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Compra'),
        ),
    ]
