# Generated by Django 6.0.3 on 2026-04-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0006_alter_movimentacao_mov_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='mov_quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade relativa à Unidade de Medida'),
        ),
    ]
