# Generated by Django 6.0.3 on 2026-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='data_adicionada',
            new_name='pro_data_adicionada',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='produto',
        ),
        migrations.AddField(
            model_name='produtos',
            name='pro_descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='pro_preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='pro_referencia',
            field=models.CharField(default='SEM-REF', max_length=200, verbose_name='Referência'),
        ),
    ]
