# Generated by Django 6.0.3 on 2026-03-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='pro_referencia',
            field=models.CharField(default='SEM-REF', max_length=30, verbose_name='Referência'),
        ),
    ]
